# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffadde417555501ca33232e3031c60e51a7f3623ee03301bc3a7db36f1f70991250fd65ae5a1287d15901eafcda61c133e464043e3e250262f04abe46d6d1884

test:
  secret_key_base: 6746674493289560efba59cc0bbea038f06eea7bbee368c7a98c1b6b2e7848dcd868fbc5c645b7ea28028d432a2d45957337c32d6b6f00ff6c5ded2101f16d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
